services:
  postgres:
    image: postgres:16
    container_name: bookdb-postgres
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bookdb-data:/var/lib/postgresql/data

volumes:
  bookdb-data:
